name = "KMCSurrogates"
uuid = "b60b8549-2b63-48dd-a9b5-d6d596d6da0a"
authors = ["Younes Hassani Abdollahi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
